language: node_js

cache:
  - apt
  - npm
  
matrix:
  fast_finish: true
  
services: mongodb

before_install:
  - chmod u+x start.sh


after_script:
  - ./start.sh 

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/08c84711c36e875930d0
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

